name: release

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calculateVersion.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Calculate version
        id: calculateVersion
        run: |
          read -r version<VERSION
          echo $version
          echo "::set-output name=version::$version"

  create-tag:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Create tag
        run: |
          git config --global user.email "reportportal.io"
          git config --global user.name "reportportal.io"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch
          git checkout master
          git tag -a v${{ needs.bump-version.outputs.version }} -m ${{ needs.bump-version.outputs.version }}
          npm version from-git
          git push origin master v${{ needs.bump-version.outputs.version }}

  create-release:
    needs: bump-version, create-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Create Release
        id: createRelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.bump-version.outputs.version }}
          release_name: Release v${{ needs.bump-version.outputs.version }}
          body: |
            Changes:
            use changelog here
          draft: false
          prerelease: false
