name: release

on:
  pull_request:
    types: [closed]

jobs:
  bump-version:
    if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Clean install of node dependencies
        run: npm ci
      - name: Calculate version type
        id: calculateVersion
        uses: amsterget/get-version-action@v2
      - name: Bump version
        run: |
          echo "The version type is ${{ steps.calculateVersion.outputs.versionType }}"
          npm version ${{ steps.calculateVersion.outputs.versionType }}

